@back_HostAddress = http://localhost:3000

GET {{back_HostAddress}}/logs/
Accept: application/json



###  
POST {{back_HostAddress}}/user
Content-Type: application/json

{
    "nome": "teste",
    "email": "teste@teste.com",
    "cpf": "12345678901",
    "celular": "12345678901",
    "password": "123456"
}

### create user
POST {{back_HostAddress}}/user
Content-Type: application/json

{
    "nome": "string",
    "email": "string", 
    "cpf": "string",
    "celular": "string",
    "password": "string"
}



###


GET {{back_HostAddress}}/
Accept: application/json


### hello request
GET {{back_HostAddress}}/hello/teste
Accept: application/json

###
@authToken = {{login.response.body.$.token}}

### login request
# @name login
POST {{back_HostAddress}}/auth/login
Content-Type: application/json

{
    "login": "teste@teste.com",
    "senha": "123456"
}




### get all users
GET {{back_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{authToken}}


### post tarefa
POST {{back_HostAddress}}/tarefa-template
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nome": "tesstar",
  "idRotina": 1,
  "pai": null,
  "prioridade": 1,
  "ativo": true
}

### get tarefa
GET {{back_HostAddress}}/tarefa-template/1
Accept: application/json
Authorization: Bearer {{authToken}}

### put tarefa
PUT {{back_HostAddress}}/tarefa-template/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": 1,
  "nome": "testar100",
  "idRotina": 1,
  "pai": null,
  "prioridade": 1,
  "ativo": true
}

### delete tarefa
DELETE {{back_HostAddress}}/tarefa-template/1
Authorization: Bearer {{authToken}}
Accept: application/json