@back_HostAddress = http://localhost:3000

GET {{back_HostAddress}}/logs/
Accept: application/json



###  
POST {{back_HostAddress}}/user
Content-Type: application/json

{
    "nome": "teste",
    "email": "teste@teste.com",
    "cpf": "12345678901",
    "celular": "12345678901",
    "password": "123456"
}

### create user
POST {{back_HostAddress}}/user
Content-Type: application/json

{
    "nome": "string",
    "email": "string", 
    "cpf": "string",
    "celular": "string",
    "password": "string"
}



###


GET {{back_HostAddress}}/
Accept: application/json


### hello request
GET {{back_HostAddress}}/hello/teste
Accept: application/json

###
@authToken = {{login.response.body.$.token}}

### login request
# @name login
POST {{back_HostAddress}}/auth/login
Content-Type: application/json

{
    "login": "teste@teste.com",
    "senha": "123456"
}


### get all users
GET {{back_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{authToken}}






