FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrator

WORKDIR /app

COPY back.csproj .
RUN dotnet restore

RUN dotnet tool install --global dotnet-ef --version 8.0.*

ENV PATH="${PATH}:/root/.dotnet/tools"

COPY . .

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "back.csproj"]