FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY back.csproj .
RUN dotnet restore
COPY . .

RUN dotnet tool install --global dotnet-ef --version 8.0.0
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update"]