FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Instala o 'migrate' no diretório padrão do Go
RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Verifica se o binário 'migrate' foi instalado corretamente
RUN ls -l /go/bin/migrate

# Define o PATH para incluir o diretório onde o 'migrate' foi instalado
ENV PATH="/go/bin:${PATH}"

RUN sleep 5

# Define o comando padrão para executar o 'migrate'
ENTRYPOINT ["migrate"]