// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/routines": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/create" | "/routines" | "/*";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/" | "/create" | "/routines";
  };
  "./routes/home/create.tsx": {
    id: "routes/home/create";
    page: "/create";
  };
  "./routes/home/routines.tsx": {
    id: "routes/home/routines";
    page: "/routines";
  };
  "routes/not_found.tsx": {
    id: "routes/not_found";
    page: "/*";
  };
};