// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/create": {
    params: {};
  };
  "/app/routines": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/app" | "/app/create" | "/app/routines" | "/*";
  };
  "routes/auth_check.tsx": {
    id: "routes/auth_check";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/app" | "/app/create" | "/app/routines";
  };
  "./routes/home/create.tsx": {
    id: "routes/home/create";
    page: "/app/create";
  };
  "./routes/home/routines.tsx": {
    id: "routes/home/routines";
    page: "/app/routines";
  };
  "routes/not_found.tsx": {
    id: "routes/not_found";
    page: "/*";
  };
};